name: Deploy_EC2

on:
  #Essa rotina só vai rodar quando for chamada
  workflow_call: 

jobs:
  EC2:
    #Irá rodar no Ubuntu latest somente
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
       # Nome do artefato
        name: programa # optional
    

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        #TARGET é o caminho no servidor remoto onde os arquivos do seu projeto serão enviados durante o deploy.
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"

    - name: executando SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: linuxserver.io
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        #O DBHOST é o endpoint do banco de dados que pegamos na aws
        script: |
          export HOST=${{ secrets.DBHOST }}
          export USER=${{ secrets.DBUSER }}
          export PASSWORD=${{ secrets.DBPASSWORD }}
          export DBNAME=${{ secrets.DBNAME }}
          export DBPORT=${{ secrets.DBPORT }}
          export PORT=8000
          chmod +x main
          nohup ./main &

    
